baseurl             = "https://intmainreturn0.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "zh-CN"
hasCJKLanguage 	    = true
relativeURLs	    = false
layoutdir           = "layouts"
publishdir          = "public"
theme               = "pixyll"
author              = "Zheng Luo"
title               = "int main() { return 0; }"
pygmentsuseclasses  = true
#disqusshortname     = "htfy96blog" # Comment out to disable Disqus.
pluralizelisttitles = false
pygmentsCodeFencesGuessSyntax = true

[permalinks]
blog  = "blog/:slug/"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  # search_engine = false
  twitter_username = "HTwood96"
  #disqus_shortname = "intmainreturn0-com"
  gitment_owner = "htfy96"
  gitment_repo = "blog-comments"
  gitment_id = "b4fe8342582a3995867d"
  gitment_secret = "e5d893bad1e5afbcceeb5788184a8e29b05aff14"
  paginate = 5
